<?php
namespace Modules\Apartment\Controllers;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Modules\Layouts\Controllers\BaseController;
use Psr\Log\LoggerInterface;

class Contract extends BaseController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index(){
    }

    public function create(){

        $list_dropdown = [0 => "Chọn Quận"];
        $auth_account = session()->get('auth_data')?->account_id;
        foreach ($this->LibApartment->getDistrict("code IN (1,4,7,8,10,'binhthanh','govap','binhchanh', 'nhabe')") as $d) {
            $list_apm = $this->GhApartment->get([
                'active' => 'YES',
                'district_code' => $d->code
            ]);

            foreach ($list_apm as $apm){
                $list_dropdown[$apm->id] = $this->LibApartment->getFullAddress($apm);
            }
        }
        $dropdown_apartment = form_dropdown('dropdown-apartment' , $list_dropdown, "", [
            'class' => 'form-control select2',
            'id' => 'dropdown-apartment'
        ]);

        $list_dropdown = [0 => "Chọn Sale Hỗ Trợ"];
        foreach ($this->GhUser->get(['active' => 'YES', 'account_id <>' => $auth_account]) as $user){
            $list_dropdown [$user->account_id] = mb_strtoupper($user->name);
        }

        $dropdown_support_ids = form_dropdown('dropdown-support-ids' , $list_dropdown, "", [
            'class' => 'form-control select2',
            'id' => 'dropdown-support-ids',
            'multiple' => true,
        ]);


        $breadcrumb = "Nhập hợp đồng";
        session()->remove('contract_new_progress');

        if(!session()->has('contract_new_progress')){
            session()->set('contract_new_progress', $this->getProgressNewContract());
        }

        return view('\Modules\Apartment\Views\contract\create',[
            'dropdown_apartment' => $dropdown_apartment,
            'dropdown_support_ids' => $dropdown_support_ids,
            'breadcrumb' => $breadcrumb,
        ]);
    }

    public function submitCreate(){

    }

    public function fetchMyContract():ResponseInterface{
        $account_id = session()->get('auth_data')?->account_id;
        $list_contract = $this->GhContract->get("consultant_id = {$account_id}");

        return $this->response->setJSON([
            'status' => true,
            'contracts' => $list_contract,
            'contract_count' => count($list_contract)
        ]);
    }

    private function getProgressNewContract($current_step = null):string{
        $arr_step = [
            ["title" => "Chọn Dự Án", "icon" => "ti ti-building-skyscraper ti-sm"],
            ["title" => "Thông tin Deal", "icon" => "ti ti-receipt-2 ti-sm"],
            ["title" => "Thông tin khách thuê", "icon" => "ti ti-id ti-sm"],
            ["title" => "Chờ Ký", "icon" => "ti ti-calendar-event ti-sm"],
            ["title" => "Đã Ký", "icon" => "ti ti-circle-check ti-sm"],
        ];


        foreach ($arr_step as $index => $step) {
            if($current_step === $step){
                $arr_step[$index] = '<span class="col-2 contract-progress-item" data-key="'.$step["title"].'">
                                        <span class="badge badge-center rounded-pill p-2 bg-label-success mx-2"><i class="'.$step["icon"].'"></i></span>
                                        <small class="d-block">'.$step["title"].'</small>
                                    </span>';
                continue;
            }

            $arr_step[$index] = '<span class="col-2">
                                    <span class="badge badge-center rounded-pill p-2 bg-label-secondary mx-2"><i class="'.$step["icon"].'"></i></span>
                                    <small class="d-block">'.$step["title"].'</small>
                                </span>';

        }

        return implode('', $arr_step);
    }


}