<?php
namespace Modules\CashFlow\Controllers;

use App\Libraries\LibApartment;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Modules\Layouts\Controllers\BaseController;
use Psr\Log\LoggerInterface;
use ZipArchive;

class Utilities extends BaseController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }


    public function calculate_money()
    {
        $denominations = [
            1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 500000
        ];

        return view('\Modules\CashFlow\Views\utilities\calculate_money.php',[
            'denominations' => $denominations,
        ]);
    }
}