<?php
namespace Modules\Auth\Controllers;

use App\Libraries\LibAuth;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Modules\Layouts\Controllers\BaseController;
use Psr\Log\LoggerInterface;


class Login extends BaseController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }


    public function submitLogin():ResponseInterface
    {
        if(is_login()){
            return $this->response->setJSON([
                'status' => false,
                'msg' => 'Bạn đã đăng nhập',
            ]);
        }

        $phone_number = $this->request->getPost('phone_number');
        $password = $this->request->getPost('password');

        if(empty($phone_number) ||  empty($password)){
            return $this->response->setJSON([
                'status' => false,
                'msg' => 'Vui lòng nhập ID & Mật khẩu',
            ]);
        }

        $LibAuth = new LibAuth();
        $login = $LibAuth->validateAuth(['phone_number' =>$phone_number, 'password' => $password]);

        if($login){
            return $this->response->setJSON([
                'status' => true,
                'msg' => 'Đăng nhập thành công'
            ]);
        }

        return $this->response->setJSON([
            'status' => true,
            'msg' => 'Tài khoản hoặc mật khẩu sai'
        ]);

    }

    public function submitLogout():ResponseInterface{
        session()->destroy();
        return $this->response->setJSON([
            'status' => true,
            'msg' => 'Đã đăng xuất'
        ]);
    }


}